services:
  backend:
    build: .
    container_name: petrocarga-backend-homologacao
    restart: unless-stopped
    networks:
      petrocarga-backend-hml-network:
      cptrans-gateway:
        aliases:
          - petrocarga-back-hml
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}

networks:
  petrocarga-backend-hml-network:
    driver: bridge
  
  cptrans-gateway:
    external: true
    name: cptrans-gateway