services:
  backend-local:
    build: .
    container_name: petrocarga-backend-local
    networks:
      - petrocarga-backend-network
      - cptrans-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}

networks:
  petrocarga-backend-network:
    driver: bridge
  
  cptrans-gateway:
    external: true
    name: cptrans-gateway