spring:
    config:
        activate:
            on-profile: local

    datasource:
        url: jdbc:postgresql://localhost:5432/petrocarga
        username: postgres
        password: 123456
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 5
    jpa:
        show-sql: true
    flyway:
        url: jdbc:postgresql://localhost:5432/petrocarga
        user: postgres
        password: 123456

app:
    firebase-push-notification:
        enabled: false
        credentials: "classpath:firebase-service-account.json"
    cookie-settings:
        secure: false
        same-site: Lax
    mailSender:
        enabled: true

logging:
    level:
        org:
            hibernate:
                sql: info